
#ifndef __DS18B20_H
#define __DS18B20_H


#define DQ P3_4

bit DS18B20_Init();														// Ham khoi tao DS18B20
unsigned char ds18b20_readbyte(void);					// Ham doc 1 byte tu DS18b20 ra ngoai
void ds18b20_writebyte(unsigned char Data);		// Ham viet 1 byte vao DS18b20
float ds18b20_readtemp(void);									// Ham chuyen doi va tra ve gia tri nhiet do

#endif
// ------------------END OF FILE--------------------
// -------------------------------------------------